@startuml
'https://plantuml.com/class-diagram

hide empty members

    abstract class ChoicePanel extends GamePanel{
        +resizeComponents()
        ..
        +description()
        +image()
        +acceptButtonText()
        +declineButtonText()
    }
    note right of ChoicePanel::resizeComponents
        Template method
    end note

    class BuyFoodPanel extends ChoicePanel{
        +description()
        +image()
        +acceptButtonText()
        +declineButtonText()
    }

    class EncounterPanel extends ChoicePanel{
        +description()
        +image()
        +acceptButtonText()
        +declineButtonText()
    }

    abstract class GamePanel{

    }

@enduml