@startuml
'https://plantuml.com/class-diagram

interface MinigameManager
class MinigameManagerImpl implements MinigameManager
abstract class Minigame
class BenchStrategy implements Minigame
class LatStrategy implements Minigame
class SquatStrategy implements Minigame

MinigameManagerImpl --* Minigame

@enduml