@startuml
'https://plantuml.com/class-diagram

class MinigameStatistics << (R, yellow) >> {
    - int numReps
    - int mistakes
    ...
}

abstract class Minigame implements MinigameStateHandler{
    + notStarted()
    + repReached()
    + miniGameEndedWon()
    + miniGameEndedLost()
    + notifyUserAction()
    + {abstract} MinigameStatistics getMinigameStatistics()
}

class BenchStrategy extends Minigame{
    + running()
    + validPress()
    + invalidPress()

}

class LatStrategy extends Minigame{
    ...

}

class SquatStrategy extends Minigame{
    ...

}
MinigameStatistics .up.* BenchStrategy
MinigameStatistics .up.* LatStrategy
MinigameStatistics .up.* SquatStrategy

@enduml